name: Build & Test after push to main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: adopt
          java-version: 15
          java-package: jdk
          architecture: x64
      - name: Build with Maven
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -s .github/settings.xml -B verify
